[tool.isort]
name = "api-impulsogov"
description = "API que serve aos projetos da ImpulsoGov, atendendo hoje ao Impulso Previne e Saúde Mental."
version = "0.1.0"
profile = "black"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ImpulsoGov/api-webapp"
[tool.pytest.ini_options]
pythonpath = [
    "."
]
testpaths = [
    "tests"
]
