# flake8: noqa: F401
from .caps_usuarios_novos_perfil import UsuariosNovosPerfil
from .caps_usuarios_novos_perfil_cid import UsuariosNovosPorCID
from .caps_usuarios_novos_perfil_genero_idade import UsuariosNovosPorGeneroEIdade
from .caps_usuarios_novos_resumo import UsuariosNovosResumo
