# flake8: noqa: F401
from .ambulatorio_procedimentos_por_profissional_por_hora import AmbulatorioProcedimentosPorProfissional
from .ambulatorio_atendimentos_resumo import AmbulatorioAtendimentoResumo
from .ambulatorio_atendimentos_resumo_ultimo_mes import AmbulatorioAtendimentoResumoUltimoMes
from .ambulatorio_usuarios_perfil import AmbulatorioUsuariosPerfil

