name: ci

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Copia arquivos do repositório
        uses: actions/checkout@v3
      - name: Seta versão do python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.10"
      - name: Instala dependências
        run: pip install -r dev-requirements.txt

      - name: Roda verificador de formatação (black)
        run: black -l 90 --check .
      - name: Roda verificador de ordem dos imports (isort)
        run: isort --check app
      - name: Roda verificador de tipagem (mypy)
        run: mypy app
        continue-on-error: true
      - name: Roda linter (flake8)
        run: flake8 app tests
        continue-on-error: true
      - name: Roda testes (pytest)
        run: pytest
